sequenceDiagram
    autonumber
    Note right of User: Truncated 565 calls to 100 for performance
    Global_analyzer_js->>Object_getOwnPropertyDescriptor: Object.getOwnPropertyDescriptor()
    Global_analyzer_js->>Object_defineProperty: Object.defineProperty()
    Global_analyzer_js->>Object_defineProperty: Object.defineProperty()
    Global_analyzer_js->>_function__________var_ownKeys___function_o____________ownKeys___Object_getOwnPropertyNames____function__o________________var_ar___________________for__var_k_in_o__if__Object_prototype_hasOwnProperty_call_o__k___ar_ar_length____k______________return_ar_____________________return_ownKeys_o______________return_function__mod____________if__mod____mod___esModule__return_mod__________var_result_______________if__mod____null__for__var_k___ownKeys_mod___i___0__i___k_length__i____if__k_i_______default_____createBinding_result__mod__k_i______________setModuleDefault_result__mod___________return_result___________: (function () {
    var ownKeys = function(o) {
...()
    ownKeys->>Object_prototype_hasOwnProperty_call: Object.prototype.hasOwnProperty.call()
    ownKeys->>ownKeys: ownKeys()
    Global_analyzer_js->>ownKeys: ownKeys()
    Global_analyzer_js->>__createBinding: __createBinding()
    Global_analyzer_js->>__setModuleDefault: __setModuleDefault()
    Global_analyzer_js->>Object_defineProperty: Object.defineProperty()
    Global_analyzer_js->>__importDefault: __importDefault()
    Global_analyzer_js->>require: require()
    Global_analyzer_js->>__importStar: __importStar()
    Global_analyzer_js->>require: require()
    Global_analyzer_js->>__importStar: __importStar()
    Global_analyzer_js->>require: require()
    init->>web_tree_sitter_1_default_init: web_tree_sitter_1.default.init()
    init->>path_join: path.join()
    init->>fs_existsSync: fs.existsSync()
    init->>web_tree_sitter_1_default_Language_load: web_tree_sitter_1.default.Language.load()
    init->>this_languages_set: this.languages.set()
    init->>console_error: console.error()
    init->>this_languages_get: this.languages.get()
    init->>this_parser_setLanguage: this.parser.setLanguage()
    getLanguageForFile->>path_extname_filePath__slice_1__toLowerCase: path.extname(filePath).slice(1).toLowerCase()
    getLanguageForFile->>path_extname_filePath__slice: path.extname(filePath).slice()
    getLanguageForFile->>path_extname: path.extname()
    getLanguageForFile->>this_languages_get: this.languages.get()
    getLanguageForFile->>this_languages_get: this.languages.get()
    getLanguageForFile->>this_languages_get: this.languages.get()
    getLanguageForFile->>this_languages_get: this.languages.get()
    getLanguageForFile->>this_languages_get: this.languages.get()
    getSymbols->>this_getLanguageForFile: this.getLanguageForFile()
    getSymbols->>this_parser_setLanguage: this.parser.setLanguage()
    getSymbols->>fs_readFileSync: fs.readFileSync()
    getSymbols->>this_parser_parse: this.parser.parse()
    getSymbols->>filePath_endsWith: filePath.endsWith()
    traverse->>node_child: node.child()
    traverse->>child_child: child.child()
    traverse->>child_childForFieldName: child.childForFieldName()
    traverse->>child_childForFieldName: child.childForFieldName()
    traverse->>traverse: traverse()
    traverse->>child_childForFieldName: child.childForFieldName()
    traverse->>child_childForFieldName: child.childForFieldName()
    traverse->>traverse: traverse()
    traverse->>child_childForFieldName: child.childForFieldName()
    traverse->>child_childForFieldName: child.childForFieldName()
    traverse->>traverse: traverse()
    traverse->>child_childForFieldName: child.childForFieldName()
    traverse->>child_childForFieldName: child.childForFieldName()
    traverse->>valueNode_childForFieldName: valueNode.childForFieldName()
    traverse->>traverse: traverse()
    traverse->>symbols_push: symbols.push()
    traverse->>symbols_push: symbols.push()
    traverse->>traverse: traverse()
    getSymbols->>traverse: traverse()
    getFunctionCalls->>this_getLanguageForFile: this.getLanguageForFile()
    getFunctionCalls->>this_parser_setLanguage: this.parser.setLanguage()
    getFunctionCalls->>fs_readFileSync: fs.readFileSync()
    getFunctionCalls->>this_parser_parse: this.parser.parse()
    getFunctionCalls->>filePath_endsWith: filePath.endsWith()
    traverse->>node_child: node.child()
    traverse->>calls_push: calls.push()
    traverse->>node_childForFieldName: node.childForFieldName()
    traverse->>calls_push: calls.push()
    traverse->>node_child: node.child()
    traverse->>traverse: traverse()
    getFunctionCalls->>traverse: traverse()
    Global_dumper_js->>Object_getOwnPropertyDescriptor: Object.getOwnPropertyDescriptor()
    Global_dumper_js->>Object_defineProperty: Object.defineProperty()
    Global_dumper_js->>Object_defineProperty: Object.defineProperty()
    Global_dumper_js->>_function__________var_ownKeys___function_o____________ownKeys___Object_getOwnPropertyNames____function__o________________var_ar___________________for__var_k_in_o__if__Object_prototype_hasOwnProperty_call_o__k___ar_ar_length____k______________return_ar_____________________return_ownKeys_o______________return_function__mod____________if__mod____mod___esModule__return_mod__________var_result_______________if__mod____null__for__var_k___ownKeys_mod___i___0__i___k_length__i____if__k_i_______default_____createBinding_result__mod__k_i______________setModuleDefault_result__mod___________return_result___________: (function () {
    var ownKeys = function(o) {
...()
    ownKeys->>Object_prototype_hasOwnProperty_call: Object.prototype.hasOwnProperty.call()
    ownKeys->>ownKeys: ownKeys()
    Global_dumper_js->>ownKeys: ownKeys()
    Global_dumper_js->>__createBinding: __createBinding()
    Global_dumper_js->>__setModuleDefault: __setModuleDefault()
    Global_dumper_js->>Object_defineProperty: Object.defineProperty()
    Global_dumper_js->>__importStar: __importStar()
    Global_dumper_js->>require: require()
    Global_dumper_js->>__importStar: __importStar()
    Global_dumper_js->>require: require()
    save->>path_join: path.join()
    save->>fs_existsSync: fs.existsSync()
    save->>fs_mkdirSync: fs.mkdirSync()
    save->>this_generateDSL: this.generateDSL()
    save->>this_generateMermaid: this.generateMermaid()
    save->>path_join: path.join()
    save->>path_join: path.join()
    save->>fs_promises_writeFile: fs.promises.writeFile()
    save->>fs_promises_writeFile: fs.promises.writeFile()
    generateDSL->>new_Date___toISOString: new Date().toISOString()
    generateDSL->>files_sort: files.sort()
    generateDSL->>a_filePath_localeCompare: a.filePath.localeCompare()
    generateDSL->>path_relative: path.relative()
    generateDSL->>this_serializeSymbols: this.serializeSymbols()
    serializeSymbols->>_____repeat: "  ".repeat()
    serializeSymbols->>____symbols__sort: [...symbols].sort()
    serializeSymbols->>this_serializeSymbols: this.serializeSymbols()
    generateMermaid->>this_findContainerSymbol: this.findContainerSymbol()